/**
 * Generates the Reference pages of `docs/` from the exported constants and
 * validators — the authoring guide, the theme tokens, the action vocabulary,
 * the tool definitions and the runtime export names of every published
 * entry — so the documentation cannot drift from what the packages enforce.
 *
 *   tsx tools/docs-generate.ts            write docs/reference/**
 *   tsx tools/docs-generate.ts --check    fail (exit 1) when the committed
 *                                         pages differ from a fresh generation
 *
 * Deterministic on purpose (stable key order, no dates), so `--check` is a
 * plain byte comparison. `reference/index.mdx` is hand-written and skipped.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  ACTION_NAME,
  HTTP_METHODS,
  OUTPUT_MODES,
  PROMPT_TEXT_MAX,
  SECRET_NAME,
  TOKEN_SPECS,
  darkTheme
} from "@widgentic/core";
import {
  EXECUTE_ACTION_TOOL,
  GET_AUTHORING_GUIDE_TOOL,
  LIST_ACTIONS_TOOL,
  LIST_SCHEMAS_TOOL,
  LIST_THEMES_TOOL,
  LIST_THEME_TOKENS_TOOL,
  LIST_WIDGETS_TOOL,
  RENDER_WIDGET_TOOL,
  buildAuthoringGuide
} from "@widgentic/mcp";

const here = dirname(fileURLToPath(import.meta.url));
export const DOCS_ROOT = join(here, "..", "docs");

/** Published entries and the docs slug of each export-index page. */
export const API_ENTRIES: ReadonlyArray<{ specifier: string; slug: string; pkg: string }> = [
  { specifier: "@widgentic/core", slug: "core", pkg: "@widgentic/core" },
  { specifier: "@widgentic/core/contract", slug: "core-contract", pkg: "@widgentic/core" },
  { specifier: "@widgentic/core/adapters", slug: "core-adapters", pkg: "@widgentic/core" },
  { specifier: "@widgentic/core/mapper", slug: "core-mapper", pkg: "@widgentic/core" },
  { specifier: "@widgentic/core/catalog", slug: "core-catalog", pkg: "@widgentic/core" },
  { specifier: "@widgentic/core/theming", slug: "core-theming", pkg: "@widgentic/core" },
  { specifier: "@widgentic/core/templates", slug: "core-templates", pkg: "@widgentic/core" },
  { specifier: "@widgentic/core/actions", slug: "core-actions", pkg: "@widgentic/core" },
  { specifier: "@widgentic/core/reactive", slug: "core-reactive", pkg: "@widgentic/core" },
  { specifier: "@widgentic/designer", slug: "designer", pkg: "@widgentic/designer" },
  { specifier: "@widgentic/webmcp", slug: "webmcp", pkg: "@widgentic/webmcp" },
  { specifier: "@widgentic/mcp", slug: "mcp", pkg: "@widgentic/mcp" },
  { specifier: "@widgentic/mcp/sdk", slug: "mcp-sdk", pkg: "@widgentic/mcp" },
  { specifier: "@widgentic/mcp/authoring", slug: "mcp-authoring", pkg: "@widgentic/mcp" },
  { specifier: "@widgentic/mcp/store", slug: "mcp-store", pkg: "@widgentic/mcp" },
  { specifier: "@widgentic/mcp/store/sqlite", slug: "mcp-store-sqlite", pkg: "@widgentic/mcp" },
  { specifier: "@widgentic/mcp/store/cosmos", slug: "mcp-store-cosmos", pkg: "@widgentic/mcp" },
  { specifier: "@widgentic/mcp/secrets", slug: "mcp-secrets", pkg: "@widgentic/mcp" },
  { specifier: "@widgentic/mcp/secrets/keyvault", slug: "mcp-secrets-keyvault", pkg: "@widgentic/mcp" }
];

const TOOLS = [
  LIST_WIDGETS_TOOL,
  LIST_SCHEMAS_TOOL,
  LIST_ACTIONS_TOOL,
  LIST_THEMES_TOOL,
  LIST_THEME_TOKENS_TOOL,
  GET_AUTHORING_GUIDE_TOOL,
  RENDER_WIDGET_TOOL,
  EXECUTE_ACTION_TOOL
];

// --- MDX helpers ----------------------------------------------------------

/** Prose: escape everything MDX or Markdown would interpret — `$` included, which the docs renderer treats as a math delimiter. */
function md(text: string): string {
  return text.replace(/[\\`*_{}[\]<>$]/g, (match) => `\\${match}`);
}

/** Inline code with a fence longer than any backtick run inside. */
function code(text: string): string {
  const longest = Math.max(0, ...[...text.matchAll(/`+/g)].map((run) => run[0].length));
  const fence = "`".repeat(longest + 1);
  const padded = text.startsWith("`") || text.endsWith("`") ? ` ${text} ` : text;
  return `${fence}${padded}${fence}`;
}

/** A table cell: prose escaping plus the column separator. */
function cell(text: string): string {
  return md(text).replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");
}

function table(headers: string[], rows: string[][]): string {
  const line = (cells: string[]) => `| ${cells.join(" | ")} |`;
  return [line(headers), line(headers.map(() => "--")), ...rows.map(line)].join("\n");
}

function frontmatter(title: string, description: string): string {
  return `---\ntitle: "${title}"\ndescription: "${description.replace(/"/g, "'")}"\n---\n`;
}

function generatedNote(source: string): string {
  return `{/* Generated by \`npm run docs:generate\` from ${source} — do not edit; edit the source and regenerate. */}\n`;
}

// --- Guide navigation (the guide is JSON data; narrow at each step) --------

type Dict = Record<string, unknown>;

function isDict(value: unknown): value is Dict {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function dict(value: unknown, path: string): Dict {
  if (!isDict(value)) throw new Error(`authoring guide: ${path} is not an object`);
  return value;
}

function str(value: unknown, path: string): string {
  if (typeof value === "string") return value;
  if (typeof value === "number") return String(value);
  throw new Error(`authoring guide: ${path} is not a string`);
}

function strings(value: unknown, path: string): string[] {
  if (!Array.isArray(value)) throw new Error(`authoring guide: ${path} is not an array`);
  return value.map((item, index) => str(item, `${path}[${index}]`));
}

/** `"NAME — rest"` → paragraph with the name in bold. */
function form(text: string): string {
  const split = text.indexOf(" — ");
  if (split < 0) return `- ${md(text)}`;
  return `- **${md(text.slice(0, split))}** — ${md(text.slice(split + 3))}`;
}

function fields(entries: Dict, path: string): string {
  return table(
    ["Field", "Meaning"],
    Object.entries(entries)
      .filter(([key]) => key !== "description")
      .map(([key, value]) => [code(key), cell(str(value, `${path}.${key}`))])
  );
}

// --- Pages -----------------------------------------------------------------

function authoringContractPage(guide: Dict): string {
  const workflow = dict(guide.workflow, "workflow");
  const widget = dict(guide.widget, "widget");
  const widgetShape = dict(widget.shape, "widget.shape");
  const descriptor = dict(widgetShape.descriptor, "widget.shape.descriptor");
  const shared = dict(guide.sharedSchema, "sharedSchema");
  const sharedShape = dict(shared.shape, "sharedSchema.shape");
  const action = dict(guide.sharedAction, "sharedAction");
  const actionShape = dict(action.shape, "sharedAction.shape");
  const theme = dict(guide.theme, "theme");
  const themeShape = dict(theme.shape, "theme.shape");
  const custom = dict(theme.customVariables, "theme.customVariables");
  const rules = dict(guide.rules, "rules");
  const styles = dict(rules.styles, "rules.styles");
  const schema = dict(rules.dataSchema, "rules.dataSchema");
  const template = dict(rules.template, "rules.template");
  const reserved = strings(widget.reservedKinds, "widget.reservedKinds");

  return [
    frontmatter("Authoring contract", "The entry shapes, identifier rules, style and data-schema constraints an agent or a person must follow when drafting widgets, shared schemas and themes — derived from the live validators."),
    generatedNote("`buildAuthoringGuide()` in `packages/mcp/src/server/guide.ts` (`@widgentic/mcp`)"),
    "This page is the `get_authoring_guide` tool rendered for people. The MCP server returns the same content as JSON.",
    "## Workflow",
    md(str(workflow.summary, "workflow.summary")),
    `<Warning>${md(str(workflow.boundary, "workflow.boundary"))}</Warning>`,
    md(str(workflow.related, "workflow.related")),
    "## Widget entry",
    md(str(widgetShape.description, "widget.shape.description")),
    table(
      ["Field", "Meaning"],
      [
        [code("kind"), cell(str(widgetShape.kind, "widget.shape.kind"))],
        [code("template"), cell(str(widgetShape.template, "widget.shape.template"))],
        [code("descriptor"), cell(str(descriptor.description, "widget.shape.descriptor.description"))]
      ]
    ),
    "### Descriptor fields",
    fields(descriptor, "widget.shape.descriptor"),
    "### Reserved kinds",
    `A custom kind must not collide with the built-in kinds: ${reserved.map(code).join(", ")}.`,
    `Identifiers match ${code(str(widget.identifierPattern, "widget.identifierPattern"))}.`,
    "## Shared data schema entry",
    md(str(sharedShape.description, "sharedSchema.shape.description")),
    fields(sharedShape, "sharedSchema.shape"),
    md(str(shared.workflow, "sharedSchema.workflow")),
    "## Shared action entry",
    md(str(actionShape.description, "sharedAction.shape.description")),
    fields(actionShape, "sharedAction.shape"),
    md(str(action.workflow, "sharedAction.workflow")),
    "## Theme entry",
    md(str(themeShape.description, "theme.shape.description")),
    fields(themeShape, "theme.shape"),
    "### Custom variables",
    `Names match ${code(str(custom.namePattern, "theme.customVariables.namePattern"))}. ${md(str(custom.appliedAs, "theme.customVariables.appliedAs"))}`,
    "### Value safety",
    md(str(theme.valueSafety, "theme.valueSafety")),
    "The full token table is on [Theme tokens](/reference/theme-tokens).",
    "## Styles",
    ...["shape", "selectors", "banned", "propertyNames", "tokens"].map((key) => md(str(styles[key], `rules.styles.${key}`))),
    "## Data schema",
    ...["keywords", "pattern", "effect"].map((key) => md(str(schema[key], `rules.dataSchema.${key}`))),
    "## Data modeling",
    md(str(template.dataModeling, "rules.template.dataModeling")),
    "The template node forms and safety rules are on [Template DSL](/reference/template-dsl); per-user limits on [Limits](/reference/limits)."
  ].join("\n\n") + "\n";
}

function templateDslPage(guide: Dict): string {
  const template = dict(dict(guide.rules, "rules").template, "rules.template");
  const safety = dict(template.safety, "rules.template.safety");
  const bounds = dict(template.bounds, "rules.template.bounds");
  return [
    frontmatter("Template DSL", "Every node form a widget template may use, the safety rules the validator enforces, and the structural bounds — derived from the live validators."),
    generatedNote("`buildAuthoringGuide().rules.template` in `packages/mcp/src/server/guide.ts` (`@widgentic/mcp`)"),
    "Templates are data: they select and arrange values, and the author supplies every literal. The forms below are the complete vocabulary.",
    "## Node forms",
    strings(template.forms, "rules.template.forms").map(form).join("\n"),
    "## Safety rules",
    ["eventHandlers", "tags", "urlAttributes", "images", "markup"].map((key) => `- ${md(str(safety[key], `rules.template.safety.${key}`))}`).join("\n"),
    "## Bounds",
    table(
      ["Bound", "Value"],
      [
        ["Maximum nesting depth", code(str(bounds.maxDepth, "rules.template.bounds.maxDepth"))],
        ["Interpreted node budget per render", code(str(bounds.maxInterpretedNodes, "rules.template.bounds.maxInterpretedNodes"))]
      ]
    ),
    md(str(bounds.note, "rules.template.bounds.note")),
    "Actions bound from templates are specified on [Action definition](/reference/action-definition); entry shapes on [Authoring contract](/reference/authoring-contract)."
  ].join("\n\n") + "\n";
}

function limitsPage(guide: Dict): string {
  const limits = dict(guide.limits, "limits");
  const bounds = dict(dict(dict(guide.rules, "rules").template, "rules.template").bounds, "rules.template.bounds");
  const rows: string[][] = [
    ["Widgets per user", code(str(limits.maxWidgetsPerUser, "limits.maxWidgetsPerUser"))],
    ["Themes per user", code(str(limits.maxThemesPerUser, "limits.maxThemesPerUser"))],
    ["Shared schemas per user", code(str(limits.maxSchemasPerUser, "limits.maxSchemasPerUser"))],
    ["Shared actions per user", code(str(limits.maxActionsPerUser, "limits.maxActionsPerUser"))],
    ["Bytes per stored entry", code(str(limits.maxEntryBytes, "limits.maxEntryBytes"))],
    ["Template nodes per stored widget", code(str(limits.maxTemplateNodes, "limits.maxTemplateNodes"))],
    ["Template nesting depth", code(str(bounds.maxDepth, "rules.template.bounds.maxDepth"))],
    ["Interpreted nodes per render", code(str(bounds.maxInterpretedNodes, "rules.template.bounds.maxInterpretedNodes"))],
    ["Resolved prompt text (characters)", code(String(PROMPT_TEXT_MAX))]
  ];
  return [
    frontmatter("Limits", "The per-user and structural limits the server enforces on stored entries, templates and prompt actions — derived from the store defaults and validators."),
    generatedNote("`buildAuthoringGuide().limits` (`@widgentic/mcp`) and `PROMPT_TEXT_MAX` (`@widgentic/core`)"),
    table(["Limit", "Value"], rows),
    md(str(limits.note, "limits.note")),
    md(str(bounds.note, "rules.template.bounds.note")),
    "The http action request limits (deadline, response size, content type) are on [Action definition](/reference/action-definition)."
  ].join("\n\n") + "\n";
}

function actionDefinitionPage(guide: Dict): string {
  const template = dict(dict(guide.rules, "rules").template, "rules.template");
  const actions = dict(template.actions, "rules.template.actions");
  const actionForm = strings(template.forms, "rules.template.forms").find((entry) => entry.startsWith("ACTION"));
  if (actionForm === undefined) throw new Error("authoring guide: no ACTION form in rules.template.forms");
  return [
    frontmatter("Action definition", "The two action kinds, how a template binds them, the execution gates and request limits, and the vocabulary constants — derived from the live validators."),
    generatedNote("`buildAuthoringGuide().rules.template.actions` (`@widgentic/mcp`) and the action constants of `@widgentic/core/actions`"),
    "## Kinds",
    md(str(actions.kinds, "rules.template.actions.kinds")),
    "## Binding from a template",
    form(actionForm),
    md(str(actions.binding, "rules.template.actions.binding")),
    "## Execution",
    md(str(actions.execution, "rules.template.actions.execution")),
    "## Request limits",
    md(str(actions.limits, "rules.template.actions.limits")),
    "## Secrets",
    md(str(actions.secrets, "rules.template.actions.secrets")),
    "## Vocabulary",
    table(
      ["Constant", "Value"],
      [
        ["HTTP methods", HTTP_METHODS.map(code).join(", ")],
        ["Output modes", OUTPUT_MODES.map(code).join(", ")],
        ["Maximum resolved prompt text", `${code(String(PROMPT_TEXT_MAX))} characters`],
        ["Action names", code(ACTION_NAME.source)],
        ["Secret names", code(SECRET_NAME.source)]
      ]
    )
  ].join("\n\n") + "\n";
}

function themeTokensPage(guide: Dict): string {
  const theme = dict(guide.theme, "theme");
  const custom = dict(theme.customVariables, "theme.customVariables");
  const specs = Object.entries(TOKEN_SPECS).map(([name, spec]) => [
    code(name),
    spec.type,
    code(spec.default),
    "fallback" in spec && typeof spec.fallback === "string" ? code(spec.fallback) : "—",
    cell(spec.use)
  ]);
  const dark = Object.entries(darkTheme).flatMap(([name, value]) => (typeof value === "string" ? [[code(name), code(value)]] : []));
  return [
    frontmatter("Theme tokens", "Every --wg-* theme token with its type, light default and use, the dark preset, and the rules for custom variables and values — derived from the token registry."),
    generatedNote("`TOKEN_SPECS` and `darkTheme` in `@widgentic/core/theming`, custom-variable rules from `buildAuthoringGuide().theme`"),
    "Themes are plain maps of bare token names (no `--wg-` prefix) to CSS values. The base stylesheet defines every token at `:root`, so widget styles may reference `var(--wg-<token>)` without a fallback.",
    "## Tokens",
    table(["Token", "Type", "Light default", "Falls back to", "Use"], specs),
    "## Dark preset",
    `The \`dark\` preset is ordinary theme data — a starting point for custom themes. The names \`light\` (the defaults) and \`dark\` are reserved for it.`,
    table(["Token", "Value"], dark),
    "## Custom variables",
    `Names match ${code(str(custom.namePattern, "theme.customVariables.namePattern"))}. ${md(str(custom.appliedAs, "theme.customVariables.appliedAs"))}`,
    "## Value safety",
    md(str(theme.valueSafety, "theme.valueSafety"))
  ].join("\n\n") + "\n";
}

function mcpToolsPage(): string {
  const sections = TOOLS.flatMap((tool) => [
    `## ${tool.name}`,
    md(tool.description),
    "```json\n" + JSON.stringify(tool.inputSchema, null, 2) + "\n```"
  ]);
  return [
    frontmatter("MCP tools", `The ${TOOLS.length} tools of a widgentic MCP server — name, description as the model sees it, and the JSON Schema of each input — derived from the tool definitions.`),
    generatedNote("the `*_TOOL` definitions in `packages/mcp/src/server/definitions.ts` (`@widgentic/mcp`)"),
    "Descriptions are the exact text advertised to agents over `tools/list`; they carry the steering, so they are longer than a reference usually is.",
    ...sections
  ].join("\n\n") + "\n";
}

async function apiIndexPages(): Promise<Map<string, string>> {
  const pages = new Map<string, string>();
  for (const entry of API_ENTRIES) {
    const module = (await import(entry.specifier)) as Record<string, unknown>;
    const names = Object.keys(module).sort();
    const readme = `https://github.com/widgentic/widgentic/blob/main/packages/${entry.pkg.split("/")[1]}/README.md`;
    pages.set(
      `reference/api/${entry.slug}.mdx`,
      [
        frontmatter(entry.specifier, `Runtime exports of the ${entry.specifier} entry — generated from the package itself.`),
        generatedNote(`the runtime exports of \`${entry.specifier}\``),
        "```bash\nnpm install " + entry.pkg + "\n```",
        "```ts\nimport { " + (names[0] ?? "") + " } from \"" + entry.specifier + "\";\n```",
        "## Runtime exports",
        names.map((name) => `- ${code(name)}`).join("\n"),
        `Type-only exports are not visible at runtime; see the [package README](${readme}) and the bundled declarations.`
      ].join("\n\n") + "\n"
    );
  }
  return pages;
}

/** Every generated page: docs-relative path → content. */
export async function generateReference(): Promise<Map<string, string>> {
  const guide = buildAuthoringGuide();
  const pages = new Map<string, string>([
    ["reference/authoring-contract.mdx", authoringContractPage(guide)],
    ["reference/template-dsl.mdx", templateDslPage(guide)],
    ["reference/limits.mdx", limitsPage(guide)],
    ["reference/action-definition.mdx", actionDefinitionPage(guide)],
    ["reference/theme-tokens.mdx", themeTokensPage(guide)],
    ["reference/mcp-tools.mdx", mcpToolsPage()]
  ]);
  for (const [path, content] of await apiIndexPages()) pages.set(path, content);
  return pages;
}

export function writeReference(pages: Map<string, string>, root: string): void {
  for (const [path, content] of pages) {
    const target = join(root, path);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content);
  }
}

/** Committed pages that differ from a fresh generation, plus stale extras. */
export function compareReference(pages: Map<string, string>, root: string): string[] {
  const problems: string[] = [];
  for (const [path, content] of pages) {
    const target = join(root, path);
    if (!existsSync(target)) problems.push(`${path}: missing`);
    else if (readFileSync(target, "utf8") !== content) problems.push(`${path}: differs`);
  }
  const referenceDir = join(root, "reference");
  if (existsSync(referenceDir)) {
    const walk = (dir: string): string[] =>
      readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
        entry.isDirectory() ? walk(join(dir, entry.name)) : [join(dir, entry.name)]
      );
    for (const file of walk(referenceDir)) {
      const rel = relative(root, file).split("\\").join("/");
      if (rel === "reference/index.mdx" || !rel.endsWith(".mdx")) continue;
      if (!pages.has(rel)) problems.push(`${rel}: not generated (stale file)`);
    }
  }
  return problems;
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const pages = await generateReference();
  if (check) {
    const problems = compareReference(pages, DOCS_ROOT);
    if (problems.length > 0) {
      console.error(`docs:generate --check: ${problems.length} page(s) out of date — run \`npm run docs:generate\`\n  ${problems.join("\n  ")}`);
      process.exit(1);
    }
    console.log(`docs:generate --check: ${pages.size} pages current`);
    return;
  }
  writeReference(pages, DOCS_ROOT);
  console.log(`docs:generate: wrote ${pages.size} pages under ${relative(process.cwd(), join(DOCS_ROOT, "reference"))}`);
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
