/**
 * The docs generator is deterministic and its `--check` mode notices drift
 * (docs-site spec, "Reference pages are derived, never restated").
 */
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { compareReference, generateReference, writeReference } from "./docs-generate.js";

const dirs: string[] = [];
afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

function scratch(): string {
  const dir = mkdtempSync(join(tmpdir(), "widgentic-docs-"));
  dirs.push(dir);
  return dir;
}

describe("docs generator", () => {
  it("produces the same pages on every run and covers every reference page", async () => {
    const first = await generateReference();
    const second = await generateReference();
    expect([...first.keys()].sort()).toEqual([...second.keys()].sort());
    for (const [path, content] of first) expect(second.get(path), path).toBe(content);
    expect([...first.keys()]).toEqual(
      expect.arrayContaining([
        "reference/authoring-contract.mdx",
        "reference/template-dsl.mdx",
        "reference/limits.mdx",
        "reference/action-definition.mdx",
        "reference/theme-tokens.mdx",
        "reference/mcp-tools.mdx",
        "reference/api/core.mdx",
        "reference/api/mcp-secrets-keyvault.mdx"
      ])
    );
    expect(first.size).toBe(24);
    // No unescaped math delimiter in PROSE: the renderer typesets `$...$`
    // spans as KaTeX, and the DSL's own $-prefixed tokens must stay text.
    // Code spans and fences are exempt — math is never parsed inside them.
    for (const [path, content] of first) {
      const prose = content.replace(/```[\s\S]*?```/g, "").replace(/`[^`]*`/g, "");
      expect(prose, path).not.toMatch(/(?<!\\)\$/);
    }
    for (const [path, content] of first) {
      expect(content, path).toMatch(/^---\ntitle: ".+"\ndescription: ".+"\n---\n/);
      expect(content, path).toContain("Generated by `npm run docs:generate`");
    }
  });

  it("derives content from the live constants", async () => {
    const pages = await generateReference();
    const tools = pages.get("reference/mcp-tools.mdx") ?? "";
    for (const name of ["list_widgets", "list_schemas", "list_themes", "list_theme_tokens", "get_authoring_guide", "render_widget", "execute_action"]) {
      expect(tools).toContain(`## ${name}`);
    }
    const tokens = pages.get("reference/theme-tokens.mdx") ?? "";
    expect(tokens).toContain("`accent`");
    expect(tokens).toContain("`#2563eb`");
    expect(tokens).toContain("## Dark preset");
    const contract = pages.get("reference/authoring-contract.mdx") ?? "";
    expect(contract).toContain("`card`");
    expect(pages.get("reference/api/core.mdx")).toContain("- `validateWidgetPayload`");
  });

  it("--check reports missing, changed and stale pages", async () => {
    const pages = await generateReference();
    const root = scratch();
    expect(compareReference(pages, root).length).toBe(pages.size);
    writeReference(pages, root);
    expect(compareReference(pages, root)).toEqual([]);
    writeFileSync(join(root, "reference", "limits.mdx"), "edited by hand\n");
    writeFileSync(join(root, "reference", "stale.mdx"), "left behind\n");
    writeFileSync(join(root, "reference", "index.mdx"), "hand-written index\n");
    const problems = compareReference(pages, root);
    expect(problems).toContain("reference/limits.mdx: differs");
    expect(problems).toContain("reference/stale.mdx: not generated (stale file)");
    expect(problems).toHaveLength(2);
  });
});
